name: databricks-mlops-aws
description: Starter IaC for Databricks MLOps on AWS (Pulumi)
runtime:
  name: python
  options:
    virtualenv: venv

config:
  pulumi:tags:
    value:
      pulumi:template: databricks-mlops-aws
